### ISSUE TITLE
Address range

### ISSUE THREAD

**Issue by Zoolu74** [meeki007/node-red-contrib-i2c-lcd-adafruit-sainsmart#1]
Hello! My LСD has an address on the bus 0x3C. But the node does not allow me to apply this address. Only 0x20 to 0x27

**Comment by meeki007** [comment]
Odd, I wrote this for the MCP23017 port expander 
[https://raspi.tv/2013/using-the-mcp23017-port-expander-with-wiringpi2-to-give-you-16-new-gpio-ports-part-3](https://raspi.tv/2013/using-the-mcp23017-port-expander-with-wiringpi2-to-give-you-16-new-gpio-ports-part-3)

What unit did you buy? what I2C port expander are you using?

**Comment by meeki007** [comment]
From my documentation:

i2c Address - The Address by default is set to 0x20. This is the Address for Adafruit and sainsmart units that use the MCP23017 i2c port expander. The rang the MCP23017 uses is a hex value from 0x20 to 0x27. If you need further information please see data on the MCP23017.

**Comment by meeki007** [comment]
No Response for 8 Days. Closing Issue
