### ISSUE TITLE
Callback Function Error

### ISSUE THREAD

**Issue by PeebsATX** [meeki007/node-red-contrib-i2c-lcd-adafruit-sainsmart#2]
When I run the example script I get "TypeError [ERR_INVALID_CALLBACK]: Callback must be a function"

Not sure what I am supposed to be doing there?

**Comment by meeki007** [comment]
looking into it now.

**Comment by meeki007** [comment]
So I installed a fresh copy of **0.20.5** node-red 
and added node-red-contrib-i2c-lcd-adafruit-sainsmart 
**its BROKEN :(** 

Installed **0.18.4** node-red back on 
and added node-red-contrib-i2c-lcd-adafruit-sainsmart 
**Works fine.**

Looks like im going to have to digg into it this weekend. If you cant wait until late sunday when ill have time to look into the issue i suggest installing  0.18.4 for now.

Sorry about this.

**Comment by meeki007** [comment]
What version of node red and JS are you using ???

**Comment by PeebsATX** [comment]
Shoot, its on my RaspberryPI away from me at the moment, but I can check this afternoon. I installed it fresh just a few days ago so I think the latest. I believe NodeJS was 10.15.3 and 0.20.4 for Node-red.

and I can definitely wait! I was able to use the 20x4 node to display stuff on the LCD for now, yours was much more customizable so looking forward to it. No need to apologize thanks for being so quick to respond, appreciate your efforts meeki007!

**Comment by meeki007** [comment]
well its as i fear. I Depend on the package adafruit-i2c-lcd and back December I started this thread on it. [https://github.com/fehmer/adafruit-i2c-lcd/issues/14](https://github.com/fehmer/adafruit-i2c-lcd/issues/14)

I never got a response and forgot about it as I had Real Life work todo.

Looks like I have 2 options. Post a notice on my package contrib stating that its no longer supported.......
OR......support my software and fix it :) 

May take me a week or a month but ill fix this. You took the time to want it and all :) 
Looks like ill be writing my own work to talk to the i2c-bus dependency and remove the depends to adafruit-i2c-lcd.

Any requests as Im going to have to rewrite 70% of my code? you state your looking for more features. What are you in need of ?

**Comment by PeebsATX** [comment]
Awesome, and I will definitely think about what features I'd like as I do some more prototyping this weekend.  

What you have now is already pretty comprehensive.  Both In and Out nodes add a lot of fun opportunities. 

My use case is a remote-controlled Police Scanner. So I was planning on using your input node so I could send commands back to the scanner. 

The one feature I could think of is adding a 3rd choice as (generic HD44780 LCD) in the dropdown. I am still a bit of a noob and wasn't sure if I should have selected Adafruit or Sainsmart. So might be useful to other more inexperienced users like me to have that third option to make things a bit more straight forward. The LCD screen I bought off of Amazon is a basic one, with no RGB. So maybe some options to enable/disable certain features like color changes, or the like. Also, maybe adding support for 20x4 sized screens? I am sure they work now, but an area to customize 2 additional lines would be cool.

Just some thoughts, I'll give it some more thought this weekend. Thanks and no rush appreciate you being so responsive. I'll follow-up soon!

**Comment by meeki007** [comment]
Making headway  -- still a month out. only have 2-4hrs every weeked to peck at this :( updated main readme page to reflect the break.

**Comment by meeki007** [comment]
Updated and fixed for node-red v1.0.0 or greater.

**Comment by meeki007** [comment]
Closed
